<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="NPOI" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AddPersonForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="EditPersonForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="EditMenuForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Pages\PersonPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>